### ISSUE TITLE
Can't use variable when schema define something as boolean

### ISSUE THREAD

**Issue by RomainMou** [ansible/vscode-ansible#125]
**Describe the bug**
When something is define as boolean in the schema, like `ignore_errors` when the value is set by a variable, vscode show an error telling `Incorrect type. Expected "boolean".yaml-schema: BeremothTaskModel`, even with the filter `bool` to force the type of the variable.

**To Reproduce**
Create a task like:
```
- name: "Demo error"
  fail:
    msg: fail except in check mode
  ignore_errors: "{{ ansible_check_mode | bool }}"
 ```

**Expected behavior**
No error about the type, at least when the type is forced (if `| bool` is specified this trigger a warning in the default configuration of ansible-lint, not without, so it'll be better if this isn't needed).

**Platform:**
Be sure vscode and extension are the latest versions and report here the
operating system you used. If you used remote-ssh or WSL. Please check if the
bug can be reproduced on Linux or MacOS.

 - OS: Archlinux

**Comment by RomainMou** [comment]
Another problem link to that kind of definition:
When this is use in a `tasks`, `pre_tasks` or `post_tasks` of a playbook, like:
```
- hosts: all
  gather_facts: False
  pre_tasks:
    - name: test
      fail:
        msg: test
      ignore_errors: "{{ ansible_check_mode | bool }}"
  roles:
    - test
 ```
 
 This show two errors:
   - the type of `ignore_errors`, like said previously, 
   - one on the task level: `Missing property "action".yaml-schema: BeremothTaskModel`. The error is not present when `ignore_errors` is define by `true` or `false`.
