### ISSUE TITLE
Unexpected error code 4 from execution of: ansible-playbook --syntax-check

### ISSUE THREAD

**Issue by jamesainslie** [ansible/vscode-ansible#1800]
### Summary

`Unexpected error code 4 from execution of: ansible-playbook --syntax-check playbooks/install_dependencies.yml`
 Relating to ansible-lint :  [internal-error](https://ansible.readthedocs.io/projects/lint/rules/internal-error/)

The file in question is:
```
- name: Install packages on remote host
  hosts: host.mydomain.net # <-- This is not an error I have redacted the hostname I am using. 
  become: true
  gather_facts: false
  tasks:
    - name: Install core packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - git
        - curl
        - wget
    - name: Install uv package manager
      community.general.snap:
        name: astral-uv
        classic: true
```
This playbook is being used by the invocation of the ansible [provider](https://registry.terraform.io/providers/ansible/ansible/1.3.0) so the inventory is created dynamically.

When I run this on the command line:
```
ansible-playbook --syntax-check playbooks/install_dependencies.yml
```
I get the following output:
```
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: Could not match supplied host pattern, ignoring: host.mydomain.net
```
The playbook applies perfectly, so it seems like there is something wrong with the linter. Or it expects the presence of an inventory file, but I have tried that and it doesn't solve the problem.

I have tried to fix the warning in my output log for the Ansible Support tab, without success, not sure if this is part of the problem:
```
cmd 'ansible-lint --version' has the following error/warning: WARNING: PATH altered to include /opt/homebrew/Cellar/ansible-lint/25.1.1/libexec/bin, /opt/homebrew/Cellar/ansible-lint/25.1.1/libexec/bin :: This is usually a sign of broken local setup, which can cause unexpected behaviors.
```

Since the ansible file has no actual errors other than the warnings is there a way of disabling the linting of this specific file.

I have also tried using a `.ansible-lint` file as specified on [issue 703](https://github.com/ansible/vscode-ansible/issues/703) but I am unable to suppress the error.

These are the entries in `.ansible-lint`

```
skip_list:
  - ansible-lint 
  - ansible-lint[internal-error]
  - ansible-lint[yaml-syntax]
```

Thanks in advance.

### Extension version

25.1.0

### VS Code version

1.96.2

### Ansible Version

```shell
ansible --version
ansible [core 2.18.1]
  config file = None
  configured module search path = ['/Users/jamesainslie/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/jamesainslie/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.13.1 (main, Dec  3 2024, 17:59:52) [Clang 16.0.0 (clang-1600.0.26.4)] (/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### OS / Environment

❯ uname -a
Darwin zeus.localdomain 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:06:23 PDT 2024; root:xnu-11215.41.3~3/RELEASE_ARM64_T8132 arm64

### Relevant log output

```shell
cmd 'ansible-lint --version' has the following error/warning: WARNING: PATH altered to include /opt/homebrew/Cellar/ansible-lint/25.1.1/libexec/bin, /opt/homebrew/Cellar/ansible-lint/25.1.1/libexec/bin :: This is usually a sign of broken local setup, which can cause unexpected behaviors.
```
