### ISSUE TITLE
"Go to Definition" for import/include resources (roles/playbook/etc)

### ISSUE THREAD

**Issue by jouve** [ansible/vscode-ansible#1814]
### Problem

![Image](https://github.com/user-attachments/assets/fc08c600-422d-4742-995d-8ae32299e4c8)

"Go to Definition" does not work (import_playbook in this example, but it applies to other import/include)

### Solution

"Go to Definition" open the imported/included yaml

```
- ansible.builtin.import_playbook: dir/foo.yml # F12 on foo.yml opens foo.yml
- ansible.builtin.include_role:
        name: bar                                            # F12 on bar opens roles/bar/tasks/main.yml
- ansible.builtin.include_role:
        name: bar                                            
        tasks_from: baz                                    # F12 on baz opens roles/bar/tasks/baz.yml
...
```

### Alternatives

tried https://marketplace.visualstudio.com/items?itemName=BlauweLucht.ansible-go-to-definition, but it would be nice have this feature by default
