### ISSUE TITLE
Persistent warning about cursor position

### ISSUE THREAD

**Issue by luizkowalski** [ansible/vscode-ansible#1904]
### Summary

Hey, ever since a couple of days ago, when I'm editing any ansible file, there is this notification at the bottom that simply doesn't go away:

<img width="555" alt="Image" src="https://github.com/user-attachments/assets/eb7238b9-c843-48b8-a1c6-4a7613b224f6" />

my files do include modelines 

```yaml
# code: language=ansible

- name: Create a netplan config and copy to /etc/netplan/01-netcfg.yaml
  tags: network
  become: true
  ansible.builtin.template:
    src: netcfg.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    mode: "0600"
...
```

This is new, these files and my setup hasn't changed in months and I just now started seeing this persistent notification

### Extension version

25.3.0

### VS Code version

Cursor 0.48

### Ansible Version

```shell
ansible [core 2.18.3]
  config file = /Users/luiz/Projects/homeserver/ansible.cfg
  configured module search path = ['/Users/luiz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/luiz/Library/Caches/pypoetry/virtualenvs/homeserver-hz53Ui3w-py3.13/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/luiz/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/luiz/Library/Caches/pypoetry/virtualenvs/homeserver-hz53Ui3w-py3.13/bin/ansible
  python version = 3.13.1 (main, Dec  7 2024, 18:37:34) [Clang 16.0.0 (clang-1600.0.26.4)] (/Users/luiz/Library/Caches/pypoetry/virtualenvs/homeserver-hz53Ui3w-py3.13/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

### OS / Environment

MacOS

### Relevant log output

```shell

```
