### ISSUE TITLE
Fix handling of quotes when using inline ansible-vault encryption

### ISSUE THREAD

**Issue by jeinwag** [ansible/vscode-ansible#348]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

Currently, when using inline encryption on a quoted string, the quotes will be included as is in the resulting encrypted string.

Please compare the output of the following example when run with the unencrypted password string vs. encrypted password string:
```yaml
- hosts: localhost
  vars:
    username: johndoe
    password: 'foobar' 
  tasks:
    - name: Display something
      ansible.builtin.debug:
        msg: "Password: {{ password }}"
```
IMO the playbook should produce identical outputs in both cases.

I'll start working on a fix.

### Extension version

0.7.1

### VS Code version

1.62.3

### Ansible Version

```console
ansible [core 2.11.6] 
  config file = /workspaces/*****/ansible.cfg
  configured module search path = ['/home/vscode/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/vscode/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.2
  libyaml = True
```

### OS / Environment

macOS 12 + Ubuntu based Devcontainer
