### ISSUE TITLE
Extension suggests replacements of modules with internal implentation names

### ISSUE THREAD

**Issue by C0rn3j** [ansible/vscode-ansible#573]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

Here's my main.yaml
```yaml
- name: Clone/Update Guard git repo
  ansible.builtin.git:
    repo: 'https://github.com/thedevs-network/the-guard-bot.git'
    dest: /opt/the-guard-bot
    update: true

- name: Install npm
  community.general.pacman:
    name: npm
    state: present

- name: Install packages based on package.json.
  community.general.npm:
    path: /opt/the-guard-bot
```

running ansible-lint against it I get the following
```console
% ansible-lint main.yaml                                                         
WARNING  Listing 1 violation(s) that are fatal
git-latest: Git checkouts must contain explicit version.
main.yaml:8 Task/Handler: Clone/Update Guard git repo

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - git-latest  # Git checkouts must contain explicit version.

Finished with 1 failure(s), 0 warning(s) on 1 files.
```

That is fine.

However, in VSC, if I hover over community.general.pacman or community.general.npm, I get suggestions to replace them.

```
Use community.general.packaging.os.pacman instead.
Use community.general.packaging.language.npm instead.
```
The only place where I can find these mentioned is https://github.com/ansible-collections/community.general/blob/main/meta/runtime.yml#L1102

After talking with one of the `community.general` contributors on Matrix, it seems like it shouldn't be a thing and is a bug
```
felixfontein:
  actually doing that replacement would be a REALLY BAD idea.
  community.general.packaging.os.pacman is an implementation detail that can change even in a bugfix release and leave you with something that isn't working
  you should definitely file a bug report for the plugin
```

### Extension version

0.11.10

### VS Code version

1.69.2

### Ansible Version

```shell
ansible [core 2.13.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/c0rn3j/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/c0rn3j/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

Arch Linux
ansible-lint 6.3.0-1
