### ISSUE TITLE
How to set up formatter?

### ISSUE THREAD

**Issue by Igorgro** [ansible/vscode-ansible#597]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

Cannot set up YAML extension as formatter for ansible. I have the following line in my settings.json:
```
"[ansible]": {
    "editor.defaultFormatter": "redhat.vscode-yaml"
}
```
but when I press 'Format document', vscode complains that "There is no formatter for 'ansible' files installed".
Is it a bug with this extension, vscode-yaml extension or vscode itself?

### Extension version

0.12.30

### VS Code version

1.70.2

### Ansible Version

```shell
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/igormahov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/igormahov/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

Arch Linux

**Comment by ssbarnea** [comment]
At this moment we have no planning to make our extension a formatter, but we do use and recommend others to use [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension for formatting, especially as we know that ansible-lint formatting rules are compatible with prettier.

**Comment by Igorgro** [comment]
But why can't I setup YAML as formatter?

**Comment by ssbarnea** [comment]
What formatter you use is not limited by the extension in any way, that is a vscode setting that has nothing to do with extension itself. The fact that vscode displays all installed plugins in the dropdown, is their bug. They display extensions that have nothing to do with formatting and that they do not advertise any formatting features. I suspect this might be a regression but I am not sure.

**Comment by DeadNews** [comment]
> At this moment we have no planning to make our extension a formatter, but we do use and recommend others to use [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension for formatting, especially as we know that ansible-lint formatting rules are compatible with prettier.



`test.yml`:

```yml
---
- name: Test
  hosts: localhost

  tasks:
    - name: Test
      ansible.posix.synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: ~/test-test-test/tmux/tmux.conf, dest: /test-test-test/.config/tmux/tmux.conf }
```

`test.yml` after formatting with [esbenp.prettier-vscode](https://github.com/prettier/prettier-vscode) or [redhat.vscode-yaml](https://github.com/redhat-developer/vscode-yaml):

```yml
---
- name: Test
  hosts: localhost

  tasks:
    - name: Test
      ansible.posix.synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {
            src: ~/test-test-test/tmux/tmux.conf,
            dest: /test-test-test/.config/tmux/tmux.conf,
          }
```

ansible-lint:

```sh
❯ ansible-lint test.yml
WARNING  Listing 3 violation(s) that are fatal
yaml: wrong indentation: expected 10 but found 12 (yaml[indentation])
test.yml:12

yaml: wrong indentation: expected 10 but found 12 (yaml[indentation])
test.yml:13

yaml: wrong indentation: expected 8 but found 10 (yaml[indentation])
test.yml:14

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - yaml[indentation]  # Violations reported by yamllint.

Finished with 3 failure(s), 0 warning(s) on 1 files.
```

**Comment by bristea** [comment]
That can also be written as below:
```
- src: foo
  dest: bar
```

And for that case yamllint does not complain at all. One could argue that this might look like a [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) case and that none of the 4 involved tools are to blame: ansible-lint, yamllint, prettier or redhat.yaml extension but I am sure that any of the two formatters would be happy to receive a pull-request that improves their formatting ability and allow them to remove the boilerplate curly braces.

**Comment by DeadNews** [comment]
This is just an example snippet. Naturally, there could be a continuation:
```yml
---
- name: Test
  hosts: localhost

  tasks:
    - name: Test
      ansible.posix.synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {
            src: ~/test-test-test/tmux/tmux.conf,
            dest: /test-test-test/.config/tmux/tmux.conf,
          }
        - {
            src: ~/test-test-test/tmux/tmux1.conf,
            dest: /test-test-test/.config/tmux/tmux1.conf,
          }
        - {
            src: ~/test-test-test/tmux/tmux2.conf,
            dest: /test-test-test/.config/tmux/tmux2.conf,
          }
        - {
            src: ~/test-test-test/tmux/tmux3.conf,
            dest: /test-test-test/.config/tmux/tmux3.conf,
          }
        - {
            src: ~/test-test-test/tmux/tmux4.conf,
            dest: /test-test-test/.config/tmux/tmux4.conf,
          }
```
From https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#iterating-over-a-list-of-hashes:

```yml
---
- name: Test
  hosts: localhost

  tasks:
    - name: Add several users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - {
            name: "veryveryveryverylonguser1",
            groups: "veryveryveryverylongwheel",
          }
        - {
            name: "veryveryveryverylonguser2",
            groups: "veryveryveryverylongroot",
          }
```
Formatting is ok, it looks like a issue with `yamllint`.
