### ISSUE TITLE
syntax highlight broken on playbook handlers

### ISSUE THREAD

**Issue by ssbarnea** [ansible/vscode-ansible#628]
I was surprised to discover that `handlers:` block in playbooks is not colorized the same way as `tasks:`, see below:

![](https://sbarnea.com/ss/Screen-Shot-2022-09-17-08-15-13.50.png)

```yaml
---
- name: Example of no-handler rule
  hosts: localhost
  tasks:
    - name: Register result of a task
      ansible.builtin.file:
        path: "/tmp/foobar2"
        state: file
        mode: 0600
      register: result
      notify:
        - Second command to run
  handlers:
    - name: Second command to run
      ansible.builtin.debug:
        msg: A new file was created!
```

@priyamsahoo I have the impression that you might know what it causing this.
