### ISSUE TITLE
customize playbooks vs tasks detection

### ISSUE THREAD

**Issue by nORKy54** [ansible/vscode-ansible#670]
### Problem

My simplified folders structure:
```
plays/
├─ site.yml
├─ sub/
│  ├─ trusted_ca.yml
```
site.yml is a playbook file, but trusted_ca.yml is a tasks file included by site.yml
But, Ansible extension detect as a playbook file. My `trusted_ca.yml`:
```
- name: Install domain.crt
  ansible.builtin.include_role:
    name: my.general.install_trusted_ca
  vars:
    install_trusted_ca_from_file: "files/domain.crt"
# [ ... ]
```
Hi have an error on my first line `'ansible.builtin.include_role' is not a valid attribute for a Play`

### Solution

Customize like files extensions in vscode for ansible type ? I don't know
```
**/playbooks/sub/*.yml -> ansible-tasks
```

### Alternatives

Perhaps you can suggest me a better folder structure ?
