### ISSUE TITLE
Support unsafe strings

### ISSUE THREAD

**Issue by bluikko** [ansible/vscode-ansible#889]
### Problem

As listed in Ansible documentation https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_advanced_syntax.html#unsafe-or-raw-strings unsafe strings with `!unsafe` are not templated. But vscode-ansible still continues to parse&lite these strings as if they are templated.  
I also do not have a clue on whether this is a difficult feature request, sorry I'm just a luser of vscode-ansible.

### Solution

`!unsafe` strings should be not parsed and should be highlighted only as strings without any templating.

### Alternatives

I would not know if this would belong in the language server or otherwise somewhere else than here in `vscode-ansible`. On feedback I can re-open in an another repository.

### Additional context

For example:
```yaml
  rawvar: !unsafe "{{ should_not_be_parsed }}"
  rawvartoo: !unsafe >
    also {{ should }} not be parsed
```

The identifiers inside braces should not be highlighted in any way, the whole thing should be a plain string.
