### ISSUE TITLE
Content to assert module parameter `that` not treated as an expression

### ISSUE THREAD

**Issue by bluikko** [ansible/vscode-ansible#909]
### Summary

The module `ansible.builtin.assert` provides a parameter `that` which is a condition that does not need `{{ }}`, similarly to a `when:` expression. But currently vscode-ansible treats the value to `that` parameter as "just" a text string: it is missing syntax highlighting etc.

The value of parameter `that` for module `ansible.builtin.assert` should be highlighted as jinja similarly to value to `when`.

Maybe this is a difficult request and I debated long whether it should be a bug or a feature, but it seems like it is a bug if something that should be treated as jinja is treated as a plain text string.

Examples:
```
- name: Test assert
  ansible.builtin.assert:
    that: var_name | bool
- name: Test assert too
  ansible.builtin.assert:
    that:
      - var_name_too > 0
      - var_name_thee < 2
```
### Extension version

2.2.69

### VS Code version

1.76.2

### Ansible Version

```shell
not relevant/not used on this machine
```

### OS / Environment

Win 10 1909

### Relevant log output

```shell
not relevant?
```
